defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: "<your_consumer_key>"
    consumer_secret: "<your_consumer_secret>"

test:
  <<: *defaults

production:
  <<: *defaults


